# Generated by Django 5.2.7 on 2025-10-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackinghistory",
            name="amount",
            field=models.FloatField(editable=False),
        ),
    ]
