# Generated by Django 5.2.7 on 2025-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_requestlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlogs",
            name="request_METHOD",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
